import type { AnalysisResult } from './youtube.js';

export const DEMO_DATA: AnalysisResult = {
  "channel": {
    "id": "UCBJycsmduvYEL83R_U4JriQ",
    "handle": "@mkbhd",
    "title": "Marques Brownlee",
    "description": "MKBHD: Quality Tech Videos | YouTuber | Geek | Consumer Electronics | Tech Head | Internet Personality!\n\nbusiness@MKBHD.com\n\nNYC",
    "thumbnailUrl": "https://yt3.ggpht.com/qu4TmIaYUlS41-dJ9gZ7DUR3nilvmB5_11i6OKSdvNnBNiyOusZP1bMN6ICnuxtjFBb6ioKgRQ=s800-c-k-c0x00ffffff-no-rj",
    "subscriberCount": 20800000,
    "totalViewCount": 5316018481,
    "videoCount": 1808,
    "createdAt": "2008-03-21T15:25:54Z",
    "country": "US",
    "uploadPlaylistId": "UUBJycsmduvYEL83R_U4JriQ",
    "healthScore": 65,
    "avgEngagementRate": 3.26
  },
  "videos": [
    {
      "id": "PTd98UnJnnU",
      "title": "This TECH Knife is Insane!",
      "thumbnailUrl": "https://i.ytimg.com/vi/PTd98UnJnnU/hqdefault.jpg",
      "description": "Sorry dinner is late, I had to charge my knife",
      "publishedAt": "2026-01-16T21:56:34Z",
      "durationIso": "PT1M53S",
      "durationSeconds": 113,
      "viewCount": 25119764,
      "likeCount": 730729,
      "commentCount": 22443,
      "engagementRate": 2.998324347314728,
      "isRecent": false,
      "keywords": [
        "tech",
        "knife",
        "insane"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=PTd98UnJnnU",
      "relativeViewScore": 100,
      "isTrending": false,
      "isTopAllTime": true,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "jrzK4xL_W4Q",
      "title": "This is not normal",
      "thumbnailUrl": "https://i.ytimg.com/vi/jrzK4xL_W4Q/hqdefault.jpg",
      "description": "",
      "publishedAt": "2025-11-13T14:36:14Z",
      "durationIso": "PT59S",
      "durationSeconds": 59,
      "viewCount": 16959082,
      "likeCount": 655256,
      "commentCount": 7283,
      "engagementRate": 3.906691411716743,
      "isRecent": false,
      "keywords": [
        "normal"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=jrzK4xL_W4Q",
      "relativeViewScore": 67.5129033855573,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Nov 2025"
    },
    {
      "id": "idEAABFzpfg",
      "title": "iPhone 17/Pro/Air Impressions: Spot the Red Flags!",
      "thumbnailUrl": "https://i.ytimg.com/vi/idEAABFzpfg/hqdefault.jpg",
      "description": "Everything new from Apple's 2025 September event\n\nKeep your smartphone charged up with Ridge and get 10% off at https://geni.us/RidgePowerBank\n\nApple iPhone 17 Air: https://geni.us/Z8kz4\nApple iPhone 17 Pro: https://geni.us/qvBF\nApple iPhone 17: https://geni.us/HAo8K\nApple Watch Ultra 3: https://geni.us/J4BmPO\nApple AirPods Pro 3: https://geni.us/CFCWi\nApple Watch 11: https://geni.us/a3uY\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-09-10T08:04:59Z",
      "durationIso": "PT14M50S",
      "durationSeconds": 890,
      "viewCount": 14020667,
      "likeCount": 339501,
      "commentCount": 21504,
      "engagementRate": 2.5748061771954216,
      "isRecent": false,
      "keywords": [
        "iphone",
        "17proair",
        "impressions"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=idEAABFzpfg",
      "relativeViewScore": 55.81528154484254,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "_yOTYsFlRQY",
      "title": "The iPhone AIR",
      "thumbnailUrl": "https://i.ytimg.com/vi/_yOTYsFlRQY/hqdefault.jpg",
      "description": "First gen. Razor thin.",
      "publishedAt": "2025-09-10T02:54:04Z",
      "durationIso": "PT53S",
      "durationSeconds": 53,
      "viewCount": 12774795,
      "likeCount": 386336,
      "commentCount": 7046,
      "engagementRate": 3.079360568995432,
      "isRecent": false,
      "keywords": [
        "iphone"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=_yOTYsFlRQY",
      "relativeViewScore": 50.85555342000825,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "xIFkrVU5Krk",
      "title": "This or the iPhone?",
      "thumbnailUrl": "https://i.ytimg.com/vi/xIFkrVU5Krk/hqdefault.jpg",
      "description": "Xiaomi 17 Pro Max?",
      "publishedAt": "2025-10-15T22:19:51Z",
      "durationIso": "PT1M10S",
      "durationSeconds": 70,
      "viewCount": 12415455,
      "likeCount": 346396,
      "commentCount": 7449,
      "engagementRate": 2.850036506918192,
      "isRecent": false,
      "keywords": [
        "iphone"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=xIFkrVU5Krk",
      "relativeViewScore": 49.425046349957746,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "GAdT6gYE54U",
      "title": "Genius idea... Bad execution",
      "thumbnailUrl": "https://i.ytimg.com/vi/GAdT6gYE54U/hqdefault.jpg",
      "description": "Somebody copy this with high quality parts please",
      "publishedAt": "2025-10-03T19:57:29Z",
      "durationIso": "PT42S",
      "durationSeconds": 42,
      "viewCount": 10348333,
      "likeCount": 276094,
      "commentCount": 2548,
      "engagementRate": 2.6926269187510683,
      "isRecent": false,
      "keywords": [
        "genius",
        "idea",
        "execution"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=GAdT6gYE54U",
      "relativeViewScore": 41.19598018516416,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "Mb6H7trzMfI",
      "title": "Driving Xiaomi's Electric Car: Are we Cooked?",
      "thumbnailUrl": "https://i.ytimg.com/vi/Mb6H7trzMfI/hqdefault.jpg",
      "description": "Xiaomi (yes, that Xiaomi) made a ridiculously good car for the price.\n\nGet yourself or someone a gift they’ll actually use every day with Ridge. Get up to 47% off at https://geni.us/RidgeMKBHD\n\nAuto Focus video: https://youtu.be/sdSusCDZcDg?si=eaL2H2y5Iq-9jdem\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\n0:00 Intro\n0:34 The Xiaomi SU7\n3:06 Interior Features\n6:34 It's Modular!\n8:03 Driving Impressions\n13:39 Are we cooked?",
      "publishedAt": "2025-12-05T21:43:39Z",
      "durationIso": "PT17M25S",
      "durationSeconds": 1045,
      "viewCount": 9799444,
      "likeCount": 258358,
      "commentCount": 25555,
      "engagementRate": 2.8972358023577662,
      "isRecent": false,
      "keywords": [
        "driving",
        "xiaomis",
        "electric"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=Mb6H7trzMfI",
      "relativeViewScore": 39.01089198131002,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Dec 2025"
    },
    {
      "id": "McE6el9mn_I",
      "title": "Samsung's Secret Screen Feature",
      "thumbnailUrl": "https://i.ytimg.com/vi/McE6el9mn_I/hqdefault.jpg",
      "description": "Galaxy S26 Ultra Privacy Display feature is legitimately sweet",
      "publishedAt": "2026-02-25T21:38:47Z",
      "durationIso": "PT44S",
      "durationSeconds": 44,
      "viewCount": 8828524,
      "likeCount": 451930,
      "commentCount": 8685,
      "engagementRate": 5.2173500349548805,
      "isRecent": true,
      "keywords": [
        "samsungs",
        "secret",
        "screen"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=McE6el9mn_I",
      "relativeViewScore": 35.14572827993129,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "high",
      "publishMonth": "Feb 2026"
    },
    {
      "id": "v5lc7UAAats",
      "title": "This or Apple Vision Pro?",
      "thumbnailUrl": "https://i.ytimg.com/vi/v5lc7UAAats/hqdefault.jpg",
      "description": "",
      "publishedAt": "2025-10-24T02:20:38Z",
      "durationIso": "PT1M12S",
      "durationSeconds": 72,
      "viewCount": 8151307,
      "likeCount": 272120,
      "commentCount": 3801,
      "engagementRate": 3.3849908977787244,
      "isRecent": false,
      "keywords": [
        "apple",
        "vision"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=v5lc7UAAats",
      "relativeViewScore": 32.4497754039409,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "7gtc1DW2Tgo",
      "title": "Wait... Smart Glasses are Suddenly Good?",
      "thumbnailUrl": "https://i.ytimg.com/vi/7gtc1DW2Tgo/hqdefault.jpg",
      "description": "Trying the Meta Rayban Display glasses\n\nTrying the Orion prototypes: https://youtu.be/G0eKzU_fV00\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-09-19T17:37:19Z",
      "durationIso": "PT11M31S",
      "durationSeconds": 691,
      "viewCount": 7907609,
      "likeCount": 188716,
      "commentCount": 8637,
      "engagementRate": 2.495735436590251,
      "isRecent": false,
      "keywords": [
        "wait",
        "smart",
        "glasses"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=7gtc1DW2Tgo",
      "relativeViewScore": 31.47963093920787,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "s0EbxhQYeCA",
      "title": "iPhone 17/Pro/Air Unboxing: 1 Hot Take!",
      "thumbnailUrl": "https://i.ytimg.com/vi/s0EbxhQYeCA/hqdefault.jpg",
      "description": "Unboxing every new iPhone 17 series phone and taking a second look. Reviews incoming.\n\nCheck out the tank case at https://dbrand.com/shop/iphone-17\n\nApple iPhone 17 Air: https://geni.us/Z8kz4\nApple iPhone 17 Pro: https://geni.us/qvBF\nApple iPhone 17: https://geni.us/HAo8K\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhones provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\n0:00 Unboxing Every iPhone\n5:47 Benchmarks\n6:12 Let's talk batteries\n8:19 The most interesting Air (vs Edge)\n10:30 Hot Take\n11:28 There's more",
      "publishedAt": "2025-09-17T12:01:11Z",
      "durationIso": "PT13M17S",
      "durationSeconds": 797,
      "viewCount": 7583741,
      "likeCount": 185503,
      "commentCount": 8620,
      "engagementRate": 2.559726129887611,
      "isRecent": false,
      "keywords": [
        "iphone",
        "17proair",
        "unboxing"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=s0EbxhQYeCA",
      "relativeViewScore": 30.190335386908888,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "rZMMySvsKAA",
      "title": "The Solar Powered Aptera EV 👀",
      "thumbnailUrl": "https://i.ytimg.com/vi/rZMMySvsKAA/hqdefault.jpg",
      "description": "Straight from the Jetsons",
      "publishedAt": "2025-10-17T21:40:13Z",
      "durationIso": "PT1M57S",
      "durationSeconds": 117,
      "viewCount": 7316614,
      "likeCount": 309031,
      "commentCount": 6782,
      "engagementRate": 4.316381867350116,
      "isRecent": false,
      "keywords": [
        "solar",
        "powered",
        "aptera"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=rZMMySvsKAA",
      "relativeViewScore": 29.12692173381884,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "kBX5WH9b4M4",
      "title": "Macbook Neo Impressions: Reincarnated!",
      "thumbnailUrl": "https://i.ytimg.com/vi/kBX5WH9b4M4/hqdefault.jpg",
      "description": "The new $599 Macbook is a good deal - and it's the computer Apple tried to make 10 years ago.\nSave up to 40% off during Ridge’s anniversary sale at https://geni.us/RidgeMKBHD\nThat shirt: http://shop.MKBHD.com\n\nAffiliate Links:\nMacBook Neo: https://geni.us/JGI8B3f\nMacBook Pro M5: https://geni.us/TINvV0\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-04T22:26:34Z",
      "durationIso": "PT8M48S",
      "durationSeconds": 528,
      "viewCount": 7232896,
      "likeCount": 197223,
      "commentCount": 11343,
      "engagementRate": 2.8835752650114146,
      "isRecent": true,
      "keywords": [
        "macbook",
        "impressions",
        "reincarnated"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=kBX5WH9b4M4",
      "relativeViewScore": 28.793646309734438,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "GB0b6KFZVq0",
      "title": "AirPods Pro 3 Review: I Understand It Now!",
      "thumbnailUrl": "https://i.ytimg.com/vi/GB0b6KFZVq0/hqdefault.jpg",
      "description": "AirPods Pro 3 got upgrades in the right places. They're so damn good (for iPhones)\n\nGet protected with dbrand’s grip case at https://dbrand.com/shop/airpods\n\nApple AirPods Pro 3: https://geni.us/CFCWi\n\nMKBHD Merch: http://shop.MKBHD.com\n\nIntro Track: Jordyn Edmonds\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nHeadphones provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-09-15T12:00:56Z",
      "durationIso": "PT11M50S",
      "durationSeconds": 710,
      "viewCount": 6888373,
      "likeCount": 191489,
      "commentCount": 7414,
      "engagementRate": 2.8875178507319506,
      "isRecent": false,
      "keywords": [
        "airpods",
        "review",
        "understand"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=GB0b6KFZVq0",
      "relativeViewScore": 27.422124666457854,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "eou_g_cYCew",
      "title": "Xiaomi 17 Pro Max: An iPhone... But Better!",
      "thumbnailUrl": "https://i.ytimg.com/vi/eou_g_cYCew/hqdefault.jpg",
      "description": "This phone is absolutely built around one-upping the iPhone.\n\nSwitching from iPhone to Android video: https://youtu.be/eCR17sBh-Qw\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-10-14T21:56:26Z",
      "durationIso": "PT11M52S",
      "durationSeconds": 712,
      "viewCount": 6824583,
      "likeCount": 192647,
      "commentCount": 13984,
      "engagementRate": 3.02774543147911,
      "isRecent": false,
      "keywords": [
        "xiaomi",
        "iphone",
        "better"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=eou_g_cYCew",
      "relativeViewScore": 27.16818119788068,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "j31dmodZ-5c",
      "title": "The Problem with this Humanoid Robot",
      "thumbnailUrl": "https://i.ytimg.com/vi/j31dmodZ-5c/hqdefault.jpg",
      "description": "Rant. We have a problem.\nJoanna's WSJ video: https://youtu.be/f3c4mQty_so?si=XfZ9c5-3VKjYPeru\nThe Neo humanoid robot: https://x.com/1x_tech/status/1983233494575952138\n\nMKBHD Merch: http://shop.MKBHD.com\n\nIntro Track: Jordyn Edmonds\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-10-30T01:46:49Z",
      "durationIso": "PT16M12S",
      "durationSeconds": 972,
      "viewCount": 6476470,
      "likeCount": 203256,
      "commentCount": 20930,
      "engagementRate": 3.461546181793477,
      "isRecent": false,
      "keywords": [
        "problem",
        "humanoid",
        "robot"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=j31dmodZ-5c",
      "relativeViewScore": 25.782368019062602,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "q0aFOxT6TNw",
      "title": "iPhone 17 Pro Review: Paradox in a Box!",
      "thumbnailUrl": "https://i.ytimg.com/vi/q0aFOxT6TNw/hqdefault.jpg",
      "description": "The two-sided existence of the iPhone 17 Pro/Pro Max\n\nProtect your iPhone 17 Pro with dbrand at https://dbrand.com/iphone-17-cases\n\nAuto Focus shot on iPhone 17 Pro: https://youtu.be/n_wbyAf0Sfs?si=ZCLdLpeNV9odVbe_\nTyler Stalman Review: https://youtu.be/KIwKEIMjBLM?si=keTAWfkW1SwobxI2\nHTX Studio Review: https://youtu.be/zC7IIJCz8Dw?si=1AEb9v1WFlvzRkiM\nJerryRigEverything: https://youtu.be/KrOBzFwVzwA?si=CdL_xLH1K0dW2E20\n\nAuto Focus: http://youtube.com/AutoFocus\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\n0:00 The Pro Paradox\n1:57 Pro Cameras\n5:02 Built like a tank\n7:35 Performance\n9:11 Big Battery\n10:19 What a Thing",
      "publishedAt": "2025-09-26T21:00:43Z",
      "durationIso": "PT12M22S",
      "durationSeconds": 742,
      "viewCount": 6389327,
      "likeCount": 145504,
      "commentCount": 5262,
      "engagementRate": 2.359653841476575,
      "isRecent": false,
      "keywords": [
        "iphone",
        "review",
        "paradox"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=q0aFOxT6TNw",
      "relativeViewScore": 25.435457912741537,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "tDARtYjUiHs",
      "title": "iPhone Air Review: Beauty is Pain",
      "thumbnailUrl": "https://i.ytimg.com/vi/tDARtYjUiHs/hqdefault.jpg",
      "description": "The thinnest and most interesting iPhone in years... is a preview for an even more interesting iPhone\n\nCheck out the Ridge Power Bank and get 10% off at https://geni.us/RidgePowerBank\n\nApple iPhone 17 Air: https://geni.us/Z8kz4\n\niOS 26 Review: https://youtu.be/FXrcFeuYtq8\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhone provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\n0:00 This is iPhone Air\n2:01 Small Concerns\n4:40 Medium Concerns\n7:30 Main Concerns\n12:33 The Future Preview",
      "publishedAt": "2025-09-23T01:22:47Z",
      "durationIso": "PT16M21S",
      "durationSeconds": 981,
      "viewCount": 6063045,
      "likeCount": 149382,
      "commentCount": 7825,
      "engagementRate": 2.592872063459862,
      "isRecent": false,
      "keywords": [
        "iphone",
        "review",
        "beauty"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=tDARtYjUiHs",
      "relativeViewScore": 24.13655239754641,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Sep 2025"
    },
    {
      "id": "eGKYiPA1wio",
      "title": "God Tier Stabilization",
      "thumbnailUrl": "https://i.ytimg.com/vi/eGKYiPA1wio/hqdefault.jpg",
      "description": "S26 Ultra \"horizon lock\" is impressive",
      "publishedAt": "2026-02-26T17:00:39Z",
      "durationIso": "PT52S",
      "durationSeconds": 52,
      "viewCount": 5964868,
      "likeCount": 259249,
      "commentCount": 5359,
      "engagementRate": 4.436108225697534,
      "isRecent": true,
      "keywords": [
        "tier",
        "stabilization"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=eGKYiPA1wio",
      "relativeViewScore": 23.74571671931313,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Feb 2026"
    },
    {
      "id": "PTf_Z8A2Usc",
      "title": "This Zoom is Ridiculous",
      "thumbnailUrl": "https://i.ytimg.com/vi/PTf_Z8A2Usc/hqdefault.jpg",
      "description": "",
      "publishedAt": "2025-10-28T20:42:14Z",
      "durationIso": "PT1M25S",
      "durationSeconds": 85,
      "viewCount": 5850377,
      "likeCount": 153769,
      "commentCount": 2018,
      "engagementRate": 2.6628540348767267,
      "isRecent": false,
      "keywords": [
        "zoom",
        "ridiculous"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=PTf_Z8A2Usc",
      "relativeViewScore": 23.289936163413,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "2MdQWo9fHZs",
      "title": "OnePlus 15 Review: This is Not Normal!",
      "thumbnailUrl": "https://i.ytimg.com/vi/2MdQWo9fHZs/hqdefault.jpg",
      "description": "The OnePlus 15 is not a normal refresh.\n\nMKBHD Merch: http://MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhone provided by OnePlus for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-11-13T14:30:53Z",
      "durationIso": "PT12M52S",
      "durationSeconds": 772,
      "viewCount": 5658555,
      "likeCount": 166314,
      "commentCount": 11515,
      "engagementRate": 3.142657445231159,
      "isRecent": false,
      "keywords": [
        "oneplus",
        "review",
        "normal"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=2MdQWo9fHZs",
      "relativeViewScore": 22.526306377719155,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Nov 2025"
    },
    {
      "id": "rng_yUSwrgU",
      "title": "iPhone 17 Review: No Asterisks!",
      "thumbnailUrl": "https://i.ytimg.com/vi/rng_yUSwrgU/hqdefault.jpg",
      "description": "This is the best iPhone in years. Which can have an interesting effect on the rest of the lineup...\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhone provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-10-01T20:41:40Z",
      "durationIso": "PT11M20S",
      "durationSeconds": 680,
      "viewCount": 5519392,
      "likeCount": 159057,
      "commentCount": 5501,
      "engagementRate": 2.981451580174048,
      "isRecent": false,
      "keywords": [
        "iphone",
        "review",
        "asterisks"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=rng_yUSwrgU",
      "relativeViewScore": 21.9723083385656,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "sfyL4BswUeE",
      "title": "Smartphone Awards 2025!",
      "thumbnailUrl": "https://i.ytimg.com/vi/sfyL4BswUeE/hqdefault.jpg",
      "description": "The best (and worst) smartphones of 2025!\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\n0:00 Introduction\n1:28 Best Big Phone\n3:34 Best Small Phone\n6:09 Best Camera\n10:47 Best Value\n14:16 Best Battery\n17:04 The Design Award\n21:03 Best Foldable\n23:38 Most Improved\n25:45 Bust of the Year\n28:15 Phone of the Year",
      "publishedAt": "2025-12-08T21:54:05Z",
      "durationIso": "PT32M38S",
      "durationSeconds": 1958,
      "viewCount": 5255315,
      "likeCount": 189035,
      "commentCount": 14309,
      "engagementRate": 3.86930184013708,
      "isRecent": false,
      "keywords": [
        "smartphone",
        "awards",
        "2025"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=sfyL4BswUeE",
      "relativeViewScore": 20.92103651929214,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Dec 2025"
    },
    {
      "id": "rU9aqBv0YdY",
      "title": "What's Going on with Apple Vision Pro?",
      "thumbnailUrl": "https://i.ytimg.com/vi/rU9aqBv0YdY/hqdefault.jpg",
      "description": "This is the Vision Pro with M5.\n\nSamsung's XR headset: https://youtu.be/az5QL_NLBvg\n\nVR headsets vs Smart Glasses: https://youtu.be/_XdD-TQseU4\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nHeadset provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-10-21T17:02:11Z",
      "durationIso": "PT10M38S",
      "durationSeconds": 638,
      "viewCount": 5235840,
      "likeCount": 123171,
      "commentCount": 6588,
      "engagementRate": 2.4782842867620096,
      "isRecent": false,
      "keywords": [
        "whats",
        "going",
        "apple"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=rU9aqBv0YdY",
      "relativeViewScore": 20.843507924676363,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "NC1nzXq6Rh4",
      "title": "PROOF the Trifold is Awesome!",
      "thumbnailUrl": "https://i.ytimg.com/vi/NC1nzXq6Rh4/hqdefault.jpg",
      "description": "",
      "publishedAt": "2025-12-18T22:39:54Z",
      "durationIso": "PT52S",
      "durationSeconds": 52,
      "viewCount": 4891872,
      "likeCount": 128943,
      "commentCount": 2058,
      "engagementRate": 2.6779318837451185,
      "isRecent": false,
      "keywords": [
        "proof",
        "trifold",
        "awesome"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=NC1nzXq6Rh4",
      "relativeViewScore": 19.474195697061486,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Dec 2025"
    },
    {
      "id": "Qr4anBkL2_A",
      "title": "This is NOT an iPhone",
      "thumbnailUrl": "https://i.ytimg.com/vi/Qr4anBkL2_A/hqdefault.jpg",
      "description": "But they sure tried to make it look like one",
      "publishedAt": "2026-01-30T19:34:19Z",
      "durationIso": "PT1M8S",
      "durationSeconds": 68,
      "viewCount": 4837725,
      "likeCount": 146262,
      "commentCount": 3532,
      "engagementRate": 3.096372778527097,
      "isRecent": false,
      "keywords": [
        "iphone"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=Qr4anBkL2_A",
      "relativeViewScore": 19.258640327990342,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "Tl8RS0sR-qA",
      "title": "Google Pixel Pro Fold Review: Not Compatible!",
      "thumbnailUrl": "https://i.ytimg.com/vi/Tl8RS0sR-qA/hqdefault.jpg",
      "description": "I love using this phone, but also Pixel and foldable are opposites.\n\nAffiliate Link: Google Pixel 10 Pro Fold - https://geni.us/lxilgO\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhone provided by Google for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-10-08T17:00:26Z",
      "durationIso": "PT8M11S",
      "durationSeconds": 491,
      "viewCount": 4757586,
      "likeCount": 69981,
      "commentCount": 3021,
      "engagementRate": 1.5344336392447766,
      "isRecent": false,
      "keywords": [
        "google",
        "pixel",
        "fold"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=Tl8RS0sR-qA",
      "relativeViewScore": 18.93961264922712,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "low",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "vZdbbN3FCzE",
      "title": "The Downfall of OnePlus will be Studied",
      "thumbnailUrl": "https://i.ytimg.com/vi/vZdbbN3FCzE/hqdefault.jpg",
      "description": "The enthusiast brand arc\n\nThat sweatshirt: http://MKBHD.com\nWhy Enthusiast Brands will Betray You: https://youtu.be/FJgTKx-rg18?si=4pUmJhf5G6HZS3Cc\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\n0:00 OnePlus the Enthusiast Brand\n1:33 “Startup” Phase\n3:46 Generation 2\n5:17 Peak\n7:58 Realization\n10:46 The Jump",
      "publishedAt": "2026-01-26T19:13:01Z",
      "durationIso": "PT15M4S",
      "durationSeconds": 904,
      "viewCount": 4608845,
      "likeCount": 128485,
      "commentCount": 12932,
      "engagementRate": 3.0683826425058776,
      "isRecent": false,
      "keywords": [
        "downfall",
        "oneplus",
        "studied"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=vZdbbN3FCzE",
      "relativeViewScore": 18.347485270960348,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "FRI78tq9Eik",
      "title": "Samsung Galaxy S26/Ultra Impressions: 1 Crazy Display Feature!",
      "thumbnailUrl": "https://i.ytimg.com/vi/FRI78tq9Eik/hqdefault.jpg",
      "description": "Galaxy S26 Ultra has one pretty sick privacy display feature\n\nProtect your Samsung S26 with dbrand at http://dbrand.com/shop/s26-ultra\n\nThat shirt: http://MKBHD.com\n\nAffiliate Links:\nSamsung Galaxy S26 Ultra: https://geni.us/6Bh61\nSamsung Galaxy S26: https://geni.us/TZA66\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-02-25T18:00:45Z",
      "durationIso": "PT9M10S",
      "durationSeconds": 550,
      "viewCount": 4287849,
      "likeCount": 131443,
      "commentCount": 8200,
      "engagementRate": 3.256714497175624,
      "isRecent": true,
      "keywords": [
        "samsung",
        "galaxy",
        "s26ultra"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=FRI78tq9Eik",
      "relativeViewScore": 17.06962294709457,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Feb 2026"
    },
    {
      "id": "trsHTKqmZOk",
      "title": "Samsung Galaxy Z Tri Fold Impressions: NOW It Makes Sense!",
      "thumbnailUrl": "https://i.ytimg.com/vi/trsHTKqmZOk/hqdefault.jpg",
      "description": "Samsung's trifold is better than expected!\n\nGet your last minute gifts and save up to 47% off with Ridge at https://geni.us/RidgeMKBHD \n\nHuawei Mate XT trifold: https://youtu.be/Yv_S7KrOlfk\n\nMKBHD Merch: http://MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-12-17T22:20:33Z",
      "durationIso": "PT13M5S",
      "durationSeconds": 785,
      "viewCount": 4278000,
      "likeCount": 109156,
      "commentCount": 8088,
      "engagementRate": 2.740626460963067,
      "isRecent": false,
      "keywords": [
        "samsung",
        "galaxy",
        "fold"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=trsHTKqmZOk",
      "relativeViewScore": 17.030414776189776,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Dec 2025"
    },
    {
      "id": "iGeXGdYE7UE",
      "title": "Macbook Neo Review: Better than you Think!",
      "thumbnailUrl": "https://i.ytimg.com/vi/iGeXGdYE7UE/hqdefault.jpg",
      "description": "Macbook Neo is only $600 bucks, but it's incredibly capable and compelling at this price\n\nCheck out dbrand skins for your MacBook at https://dbrand.com/retro-macbooks\n\nThat shirt! http://shop.MKBHD.com\n\n(Affiliate Link) MacBook Neo: https://geni.us/JGI8B3f\n\nPodcast: http://youtube.com/Waveform\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\nMacBook Neo provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-10T23:40:30Z",
      "durationIso": "PT12M53S",
      "durationSeconds": 773,
      "viewCount": 4120594,
      "likeCount": 133875,
      "commentCount": 7156,
      "engagementRate": 3.4225890733229236,
      "isRecent": true,
      "keywords": [
        "macbook",
        "review",
        "better"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=iGeXGdYE7UE",
      "relativeViewScore": 16.403792647096523,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "TVsounscj4U",
      "title": "The New Siri is... Google (Explained)",
      "thumbnailUrl": "https://i.ytimg.com/vi/TVsounscj4U/hqdefault.jpg",
      "description": "Siri by Google. Makes you think.\n\nApple AI video: https://youtu.be/hz6oys4Eem4?si=v362Nuiwg8y_pPPL\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-01-13T00:26:17Z",
      "durationIso": "PT8M23S",
      "durationSeconds": 503,
      "viewCount": 3949452,
      "likeCount": 113582,
      "commentCount": 10193,
      "engagementRate": 3.1339790938084575,
      "isRecent": false,
      "keywords": [
        "siri",
        "google",
        "explained"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=TVsounscj4U",
      "relativeViewScore": 15.72248847560829,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "DqAKQwagCDg",
      "title": "Xiaomi 17 Ultra - More Camera than Phone!",
      "thumbnailUrl": "https://i.ytimg.com/vi/DqAKQwagCDg/hqdefault.jpg",
      "description": "All that Leica branding had me nervous...\n\nHead to https://www.rocketmoney.com/MKBHD and take control of your finances today with Rocket Money!\n\nModel Y Review shot on Xiaomi: https://youtu.be/MnjNgtPr3v0?si=RTW5JXr0N1k0aYeF\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhone provided by Xiaomi for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD\n\nCorrections:\n10:05 (In camera settings, there's a \"preserve settings\" menu item that can actually remembers several camera parameters including resolution!)",
      "publishedAt": "2026-01-22T19:45:23Z",
      "durationIso": "PT12M5S",
      "durationSeconds": 725,
      "viewCount": 3767045,
      "likeCount": 96258,
      "commentCount": 3789,
      "engagementRate": 2.655848284265253,
      "isRecent": false,
      "keywords": [
        "xiaomi",
        "ultra",
        "camera"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=DqAKQwagCDg",
      "relativeViewScore": 14.996339137581069,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "RvP-uVNwnXo",
      "title": "Dope Tech: STILL so good!",
      "thumbnailUrl": "https://i.ytimg.com/vi/RvP-uVNwnXo/hqdefault.jpg",
      "description": "Thanks Google for having #sponsored a portion of this video #shopwithgoogle. Look like the hero when you find the perfect gift for friends and family this year. Check out the Google Holiday 100 list: http://g.co/shopping/mkbhd\n\nRunning it back with legends of Dope Tech past!\n\nAffiliate Links:\nLogitech MX Master 4: https://geni.us/KwXNrho\nDevialet Phantom Ultimate: https://geni.us/Yn3t0v\nGalaxy Tab S11 Ultra: https://geni.us/EfAPH\nNikon ZR: https://geni.us/lB31jGc\n\nNikon ZR review from Becca F: https://youtu.be/uK7duSgRTg4?si=kT8rB1OIqN6NCdQY\nGerald Undone on Nikon ZR: https://youtu.be/RmEyP7j6P_8?si=QUXP0z6q85esN-49\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n0:00 Logitech MX Master 4\n4:41 Devialet Phantom Ultimate\n7:11 Samsung Galaxy Tab S11 Ultra\n12:11 Nikon ZR\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-11-21T19:00:50Z",
      "durationIso": "PT16M54S",
      "durationSeconds": 1014,
      "viewCount": 3668448,
      "likeCount": 88875,
      "commentCount": 2405,
      "engagementRate": 2.488245710447579,
      "isRecent": false,
      "keywords": [
        "dope",
        "tech",
        "still"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=RvP-uVNwnXo",
      "relativeViewScore": 14.603831469117306,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Nov 2025"
    },
    {
      "id": "LXmNeVLM4e4",
      "title": "PSA: You look like this",
      "thumbnailUrl": "https://i.ytimg.com/vi/LXmNeVLM4e4/hqdefault.jpg",
      "description": "AR glasses at night",
      "publishedAt": "2026-01-27T17:36:20Z",
      "durationIso": "PT28S",
      "durationSeconds": 28,
      "viewCount": 3665454,
      "likeCount": 98488,
      "commentCount": 1303,
      "engagementRate": 2.7224731233838972,
      "isRecent": false,
      "keywords": [
        "look",
        "like"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=LXmNeVLM4e4",
      "relativeViewScore": 14.591912567331445,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "Jh9pFp1oM7E",
      "title": "I shrunk down into an M5 chip",
      "thumbnailUrl": "https://i.ytimg.com/vi/Jh9pFp1oM7E/hqdefault.jpg",
      "description": "I shrunk myself down to explore the scale of transistors.\n\nWatch the companion video from @EpicSpaceman \n\nMKBHD Merch: http://shop.MKBHD.com\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-12-26T15:00:12Z",
      "durationIso": "PT11M52S",
      "durationSeconds": 712,
      "viewCount": 3470506,
      "likeCount": 248844,
      "commentCount": 9785,
      "engagementRate": 7.452198613112901,
      "isRecent": false,
      "keywords": [
        "shrunk",
        "down",
        "into"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=Jh9pFp1oM7E",
      "relativeViewScore": 13.815838397207871,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "high",
      "publishMonth": "Dec 2025"
    },
    {
      "id": "iCSg_ul3G2w",
      "title": "Google Pixel 10A Impressions: (Never) Seen This Before",
      "thumbnailUrl": "https://i.ytimg.com/vi/iCSg_ul3G2w/hqdefault.jpg",
      "description": "The biggest difference between the Pixel 10A and 9A might just be the name.\n\nMKBHD Merch: http://MKBHD.com\n\nAffiliate Link: Google Pixel 10a - https://geni.us/pC9h\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-02-18T15:00:48Z",
      "durationIso": "PT8M31S",
      "durationSeconds": 511,
      "viewCount": 3154192,
      "likeCount": 87619,
      "commentCount": 5952,
      "engagementRate": 2.966560057219091,
      "isRecent": false,
      "keywords": [
        "google",
        "pixel",
        "impressions"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=iCSg_ul3G2w",
      "relativeViewScore": 12.55661478348284,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Feb 2026"
    },
    {
      "id": "nfHRMqqO578",
      "title": "Samsung Galaxy S26 Ultra Review: There's a Catch",
      "thumbnailUrl": "https://i.ytimg.com/vi/nfHRMqqO578/hqdefault.jpg",
      "description": "The price is the most \"ultra\" thing about the S26 Ultra\n\nMKBHD Merch: http://MKBHD.com\n\nSamsung Galaxy S26 Ultra: https://geni.us/6Bh61 (Affiliate Link)\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhone provided by Samsung for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-06T20:14:58Z",
      "durationIso": "PT12M36S",
      "durationSeconds": 756,
      "viewCount": 3104320,
      "likeCount": 99441,
      "commentCount": 5939,
      "engagementRate": 3.394624265539635,
      "isRecent": true,
      "keywords": [
        "samsung",
        "galaxy",
        "ultra"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=nfHRMqqO578",
      "relativeViewScore": 12.358077886400524,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "HLUamwXQ218",
      "title": "The Problem with this “Ultra Luxury” Smartphone",
      "thumbnailUrl": "https://i.ytimg.com/vi/HLUamwXQ218/hqdefault.jpg",
      "description": "Do not buy this phone. And don’t fall for their website slop.\n\nMKBHD Merch: http://shop.MKBHD.com\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-01-09T23:21:29Z",
      "durationIso": "PT15M32S",
      "durationSeconds": 932,
      "viewCount": 2695407,
      "likeCount": 80921,
      "commentCount": 5792,
      "engagementRate": 3.217065177911907,
      "isRecent": false,
      "keywords": [
        "problem",
        "ultra",
        "luxury"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=HLUamwXQ218",
      "relativeViewScore": 10.730224217074651,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Jan 2026"
    },
    {
      "id": "KW21q_7U6Ao",
      "title": "What's on my Phone 2026!",
      "thumbnailUrl": "https://i.ytimg.com/vi/KW21q_7U6Ao/hqdefault.jpg",
      "description": "A daily driver tour.\n\nSave up to 40% with dbrand during their Black Friday sale at https://dbrand.com/bfcm-deals\n\nThe new MKBHD merch refresh: https://MKBHD.com\n\nCalendar widget: https://play.google.com/store/apps/details?id=com.candl.auge&hl=en_US\nBlip: https://blip.net/\nRaindrop: https://raindrop.io/\n\nNuecast: https://neuecast.app/\nAthlytic: https://www.athlyticapp.com/\n\nApps You'll ACTUALLY Use: https://youtu.be/vC9N7PgIvEM?si=P1isCJ6vdQaMANFz\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-11-26T19:27:30Z",
      "durationIso": "PT13M10S",
      "durationSeconds": 790,
      "viewCount": 2507554,
      "likeCount": 67900,
      "commentCount": 2666,
      "engagementRate": 2.8141368042323314,
      "isRecent": false,
      "keywords": [
        "whats",
        "phone",
        "2026"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=KW21q_7U6Ao",
      "relativeViewScore": 9.982394739058854,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Nov 2025"
    },
    {
      "id": "n4Xe6yQ1jIs",
      "title": "This feels illegal",
      "thumbnailUrl": "https://i.ytimg.com/vi/n4Xe6yQ1jIs/hqdefault.jpg",
      "description": "",
      "publishedAt": "2025-11-26T01:27:07Z",
      "durationIso": "PT47S",
      "durationSeconds": 47,
      "viewCount": 2344554,
      "likeCount": 94271,
      "commentCount": 2205,
      "engagementRate": 4.114897758806153,
      "isRecent": false,
      "keywords": [
        "feels",
        "illegal"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=n4Xe6yQ1jIs",
      "relativeViewScore": 9.333503292467238,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Nov 2025"
    },
    {
      "id": "F1zYatpqNSc",
      "title": "The HOTTEST Phone",
      "thumbnailUrl": "https://i.ytimg.com/vi/F1zYatpqNSc/hqdefault.jpg",
      "description": "The most unnecessary easter egg. Well played",
      "publishedAt": "2025-10-08T13:11:17Z",
      "durationIso": "PT28S",
      "durationSeconds": 28,
      "viewCount": 2267247,
      "likeCount": 49263,
      "commentCount": 466,
      "engagementRate": 2.1933649046619093,
      "isRecent": false,
      "keywords": [
        "hottest",
        "phone"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=F1zYatpqNSc",
      "relativeViewScore": 9.025749604972404,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Oct 2025"
    },
    {
      "id": "D4QyStJWgCc",
      "title": "Nothing Phone 4A/Pro Review: I Have a Theory",
      "thumbnailUrl": "https://i.ytimg.com/vi/D4QyStJWgCc/hqdefault.jpg",
      "description": "Nothing isn't making a flagship phone this year. But these phones are their bread and butter.\n\nMKBHD Merch: http://shop.MKBHD.com\n\n(Affiliate Link) Nothing 4a Pro: https://geni.us/NKQo\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nPhones provided by Nothing for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-19T13:01:11Z",
      "durationIso": "PT12M4S",
      "durationSeconds": 724,
      "viewCount": 2217930,
      "likeCount": 67950,
      "commentCount": 2747,
      "engagementRate": 3.187521698159996,
      "isRecent": true,
      "keywords": [
        "nothing",
        "phone",
        "4apro"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=D4QyStJWgCc",
      "relativeViewScore": 8.829422123551797,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "wRaDbRjVrc4",
      "title": "Samsung Galaxy Buds 4 Pro Review: Better than AirPods!",
      "thumbnailUrl": "https://i.ytimg.com/vi/wRaDbRjVrc4/hqdefault.jpg",
      "description": "Galaxy Buds 4 Pro are sneaky winners!\n\nMKBHD Merch: http://shop.MKBHD.com\n\nAffiliate Link: Galaxy Buds 4 Pro - https://geni.us/Ek9oru\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nEarbuds provided by Samsung for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-02-28T22:55:15Z",
      "durationIso": "PT8M51S",
      "durationSeconds": 531,
      "viewCount": 2209941,
      "likeCount": 75367,
      "commentCount": 3405,
      "engagementRate": 3.564439050635288,
      "isRecent": true,
      "keywords": [
        "samsung",
        "galaxy",
        "buds"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=wRaDbRjVrc4",
      "relativeViewScore": 8.797618480810568,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Feb 2026"
    },
    {
      "id": "zPAY2VxfFBk",
      "title": "The Problem with these Smartphone Batteries",
      "thumbnailUrl": "https://i.ytimg.com/vi/zPAY2VxfFBk/hqdefault.jpg",
      "description": "Silicon carbon batteries are kinda incredible, but for some reason aren't everywhere yet...\n\nMKBHD Merch: http://MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-02-06T21:03:37Z",
      "durationIso": "PT8M32S",
      "durationSeconds": 512,
      "viewCount": 2157071,
      "likeCount": 85272,
      "commentCount": 6372,
      "engagementRate": 4.248538875169153,
      "isRecent": false,
      "keywords": [
        "problem",
        "these",
        "smartphone"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=zPAY2VxfFBk",
      "relativeViewScore": 8.587146758225913,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Feb 2026"
    },
    {
      "id": "Qqyp00JPJZI",
      "title": "\"Siri Isn't That Bad\"",
      "thumbnailUrl": "https://i.ytimg.com/vi/Qqyp00JPJZI/hqdefault.jpg",
      "description": "I expected nothing less from you all\n\nSave up to 47% with Ridge’s Black Friday sales event at https://ridge.com/MKBHD\n\n@JxmyHighroller: https://www.youtube.com/@JxmyHighroller\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-11-28T19:35:27Z",
      "durationIso": "PT18M48S",
      "durationSeconds": 1128,
      "viewCount": 1965978,
      "likeCount": 61791,
      "commentCount": 5334,
      "engagementRate": 3.4143311878362828,
      "isRecent": false,
      "keywords": [
        "siri",
        "isnt"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=Qqyp00JPJZI",
      "relativeViewScore": 7.8264190698606875,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Nov 2025"
    },
    {
      "id": "yWI33R4xyIc",
      "title": "Apple Studio Display XDR Review: We're All Pros Now!",
      "thumbnailUrl": "https://i.ytimg.com/vi/yWI33R4xyIc/hqdefault.jpg",
      "description": "The Studio Display XDR is really good. And really expensive.\n\nMKBHD Merch: http://shop.MKBHD.com\n\nApple Studio Display XDR: https://geni.us/eVYQk (Affiliate Link)\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nDisplay provided by Apple for review.\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-09T20:01:01Z",
      "durationIso": "PT10M42S",
      "durationSeconds": 642,
      "viewCount": 1839902,
      "likeCount": 53242,
      "commentCount": 2702,
      "engagementRate": 3.040596727434396,
      "isRecent": true,
      "keywords": [
        "apple",
        "studio",
        "display"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=yWI33R4xyIc",
      "relativeViewScore": 7.324519450103114,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "eXa2ndhmatI",
      "title": "The Windows Laptop Problem",
      "thumbnailUrl": "https://i.ytimg.com/vi/eXa2ndhmatI/hqdefault.jpg",
      "description": "There are really good Windows laptops - but how can they compete?\n\nMKBHD Color Picker Sticker Pack: https://geni.us/tAIya9\n\n(Affiliate Links)\nMacBook Neo: https://geni.us/AATWro\nMacBook Pro M5 16”: https://geni.us/6RMSTm\nDell XPS 14: https://howl.link/suo5v5pd7a9ra\nAcer Aspire 16: https://geni.us/NSQ3Rg7\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-25T18:25:28Z",
      "durationIso": "PT10M49S",
      "durationSeconds": 649,
      "viewCount": 1561479,
      "likeCount": 71758,
      "commentCount": 5922,
      "engagementRate": 4.974770714175471,
      "isRecent": true,
      "keywords": [
        "windows",
        "laptop",
        "problem"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=eXa2ndhmatI",
      "relativeViewScore": 6.21613722167135,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "j2rszuZ-9PY",
      "title": "Reviewing Everything on my Desk! (2026)",
      "thumbnailUrl": "https://i.ytimg.com/vi/j2rszuZ-9PY/hqdefault.jpg",
      "description": "Everything I've had on my desk for years in 1 video.\n\nBudget version of the same setup: https://youtu.be/fMp3TPlEBQg?si=jF9Nd5sxVvsoEPeI\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\nLinks (Affiliate):\nXDesk Air Pro: https://www.xdesk.com/air-pro\nHerman Miller Embody: https://amzn.to/4dl29m3\nMac Pro: https://www.apple.com/mac-pro/\nPro Display XDR: https://www.apple.com/studio-display-xdr/\nGrovemade monitor shelf: https://grovemade.com/product/wood-desk-shelf/?initial=342\nApollo Twin Gen 2: https://amzn.to/4bFlYmZ\nYamaha HS8: https://amzn.to/4rC9NMD\nSennheiser HD650: https://amzn.to/4rvf2gM\nBelkin charging station: https://amzn.to/4luFXbq\nRainy 75 Lite keyboard: https://amzn.to/3N10KGU\nMX Master 4: https://amzn.to/46XKYTP\nArtisan mousepad: https://amzn.to/414YXUo\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2026-03-14T20:55:28Z",
      "durationIso": "PT15M31S",
      "durationSeconds": 931,
      "viewCount": 1519044,
      "likeCount": 49694,
      "commentCount": 2048,
      "engagementRate": 3.4062212812795414,
      "isRecent": true,
      "keywords": [
        "reviewing",
        "everything",
        "desk"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=j2rszuZ-9PY",
      "relativeViewScore": 6.047206494455919,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Mar 2026"
    },
    {
      "id": "v-sCZN3FbR0",
      "title": "Every Mistake I Made in 2025",
      "thumbnailUrl": "https://i.ytimg.com/vi/v-sCZN3FbR0/hqdefault.jpg",
      "description": "I miss annotations.\n\nMKBHD Merch: http://shop.MKBHD.com\n\nPlaylist of MKBHD Intro music: https://goo.gl/B3AWV5\n\n~\nhttp://twitter.com/MKBHD\nhttp://instagram.com/MKBHD\nhttp://facebook.com/MKBHD",
      "publishedAt": "2025-12-23T00:51:58Z",
      "durationIso": "PT13M45S",
      "durationSeconds": 825,
      "viewCount": 1283850,
      "likeCount": 55925,
      "commentCount": 2499,
      "engagementRate": 4.550687385598006,
      "isRecent": false,
      "keywords": [
        "every",
        "mistake",
        "made"
      ],
      "youtubeUrl": "https://youtube.com/watch?v=v-sCZN3FbR0",
      "relativeViewScore": 5.11091585096102,
      "isTrending": false,
      "isTopAllTime": false,
      "engagementTier": "normal",
      "publishMonth": "Dec 2025"
    }
  ],
  "insights": [
    {
      "id": "strategy",
      "type": "strategy",
      "icon": "🚀",
      "title": "Viral 'This X' & Key Brand Tech",
      "body": "Videos like 'This TECH Knife is Insane!' (25.1M views) and 'Samsung's Secret Screen Feature' (315K views/day) dominate. Short, viral tech hooks with major brands like Apple/Samsung drive top performance.",
      "stat": "25.1M views (top video)",
      "confidence": "high"
    },
    {
      "id": "timing",
      "type": "timing",
      "icon": "⏰",
      "title": "Wednesdays & Fridays Drive Highest VpD",
      "body": "Wednesday posts average 116,398 views/day, closely followed by Friday at 98,094 views/day. Publishing on these peak days consistently outperforms the rest of the week.",
      "stat": "Wed 116,398 VpD avg",
      "confidence": "high"
    },
    {
      "id": "formula",
      "type": "formula",
      "icon": "🧪",
      "title": "Short Videos with Intriguing Titles Excel",
      "body": "'Samsung's Secret Screen Feature' (44s, 315K views/day) and 'God Tier Stabilization' (52s, 213K views/day) lead the pack. Videos under 2 minutes with curiosity-driven titles generate exceptional views/day.",
      "stat": "Top 44s video: 315K VpD",
      "confidence": "high"
    },
    {
      "id": "trajectory",
      "type": "trajectory",
      "icon": "📈",
      "title": "Significant Growth in Views Per Day",
      "body": "2026 videos average 165,389 views/day — a +263% jump from Oct 2025's 45,581 views/day. The channel is in a strong acceleration phase driven by short-form viral content.",
      "stat": "+263% growth since Oct 2025",
      "confidence": "high"
    }
  ],
  "fetchedAt": "2026-03-26T07:17:39.053Z",
  "isDemo": true
} as AnalysisResult;
