kind = "web"
previewPath = "/"
title = "VidMetrics"
version = "1.0.0"
id = "artifacts/vidmetrics"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22093

[services.development]
run = "pnpm --filter @workspace/vidmetrics run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vidmetrics", "run", "build" ]
publicDir = "artifacts/vidmetrics/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22093"
BASE_PATH = "/"
